theme: jekyll-theme-hacker
title: ➜  ~
description: Playing Hacks and Stuffs!.
show_downloads: false
show_repo: false

safe: true

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  - jekyll-remote-theme
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

gem "github-pages", group: :jekyll_plugins
