# Use only one theme
# theme: jekyll-theme-hacker
remote_theme: pages-themes/midnight@v0.2.0

title: ➜  ~
description: Playing Hacks and Stuffs!
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

whitelist:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Remove any gem configuration here
# gem "github-pages", group: :jekyll_plugins
